name: 'Workflow dispatch 테스트'

on:
  workflow_dispatch:
    inputs:
      branch:
        description: '배포 Branch'
        required: true
        type: choice
        options:
          - projecta/**

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.ref }}
    